feat: `ReSegmented`分段控制器新增`size`属性，以便适配不同的场景
pure-admin/vue-pure-admin pull request #1016
Opened 2024-03-23 03:45 UTC by QFifteen

为`ReSegmented`分段控制器新增`size`属性，`size` 属性用于配置尺寸，来适应不同的场景需求
定义了三种尺寸：大(`large`)、默认(`default`)、小(`small`)

尺寸样式均参考自[Ant Design(Segmented)](https://ant-design.antgroup.com/components/segmented-cn#segmented-demo-size)，高度、边距等样式基本保持一致

代码实现参考自[Ant Design Vue](https://github.com/vueComponent/ant-design-vue/tree/main/components/segmented)

已完善组件示例，它现在是这样的：
![test](https://github.com/pure-admin/vue-pure-admin/assets/66454152/dca2ec69-47a3-4c85-b30a-2df4f8f70a93)

2024-03-23 04:02 UTC, xiaoxian521 requested changes

2024-03-23 04:02 UTC, xiaoxian521 commented on src/components/ReSegmented/src/index.tsx
> -    if (props.block) {
去掉 `props.block` 的原因是什么呢

2024-03-23 05:36 UTC, QFifteen commented on src/components/ReSegmented/src/index.tsx
> -    if (props.block) {
确保当前项的样式跟着尺寸自适应

否则，它会变成这样：
![test2](https://github.com/pure-admin/vue-pure-admin/assets/66454152/f2018f86-c448-4090-9e7a-fd31a349432a)

2024-03-23 08:03 UTC, xiaoxian521 commented on src/components/ReSegmented/src/index.tsx
> -    if (props.block) {
那再监听下 size 变化 然后调用这个自适应哈 用户没有设置 不加这个 防止造成额外性能消耗

2024-03-23 09:56 UTC, QFifteen commented on src/components/ReSegmented/src/index.tsx
> -    if (props.block) {
好的，我已调整

2024-03-24 05:54 UTC, xiaoxian521 commented
nice! ❤️

2024-03-24 05:55 UTC, merged