feat(ReText): 新增ReText组件 - 基于El-Text, 增加自动省略显示Tooltip功能, 支持多行省略, 高可复用性
pure-admin/vue-pure-admin pull request #898
Opened 2024-01-26 12:55 UTC by WitMiao

1. feat(ReText): 新增ReText组件 - 基于El-Text, 增加自动省略显示Tooltip功能, 支持多行省略，高可复用性
2. perf(Menu): 改用ReText实现菜单超出显示Tooltip功能, 精简大量代码

2024-01-26 15:25 UTC, xiaoxian521 commented
很不错的`pr`

有几点反馈：  
1. 左边是修改后的菜单 ，右边是未修改的，右边是正确的 需要和其保持一致

<img width="418" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/4cd035d8-64e8-4c78-b5b9-79ca275adf5f">

2. 可以使用 [VueTippy](https://vue-tippy.netlify.app/basic-usage) 去替换 `el-tooltip` ，因为 `VueTippy` 基于 [tippyjs](https://atomiks.github.io/tippyjs/) 封装，它表现很专业，一方便是动画效果，另一方便是在不该渲染的时候它绝对不会渲染，这对于性能改进是不错的，平台已经全局注册了它 https://github.com/pure-admin/vue-pure-admin/blob/main/src/main.ts#L48-#L54

2024-01-27 04:11 UTC, WitMiao commented
> 很不错的`pr`
> 
> 有几点反馈：
> 
> 1. 左边是修改后的菜单 ，右边是未修改的，右边是正确的 需要和其保持一致
> 
> <img alt="image" width="418" src="https://private-user-images.githubusercontent.com/44761321/300026121-4cd035d8-64e8-4c78-b5b9-79ca275adf5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMjcxMzYsIm5iZiI6MTcwNjMyNjgzNiwicGF0aCI6Ii80NDc2MTMyMS8zMDAwMjYxMjEtNGNkMDM1ZDgtNjRlOC00Yzc4LWI1YjktNzljYTI3NWFkZjVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDAzNDAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmNTdjMWE4ZDM3MTQyM2UzNDkwMGIwMzI2NzQ4YWYzYWJkYjhjMGI3ZWU2NTA2OTEyODU0YWFiY2ZjMWM2OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y29wnQWvXc_UJGIQgHDpYsOLvV3cJJlqvDVCQQM3yZ8">
> 2. 可以使用 [VueTippy](https://vue-tippy.netlify.app/basic-usage) 去替换 `el-tooltip` ，因为 `VueTippy` 基于 [tippyjs](https://atomiks.github.io/tippyjs/) 封装，它表现很专业，一方面是动画效果，另一方面是在不该渲染的时候它绝对不会渲染，这对于性能改进是不错的，平台已经全局注册了它 https://github.com/pure-admin/vue-pure-admin/blob/main/src/main.ts#L48-#L54

好的，我修改一下，感谢反馈

2024-01-27 08:37 UTC, WitMiao commented
@xiaoxian521 修改完毕，看看还有没有优化空间

2024-01-27 08:47 UTC, xiaoxian521 commented
这个`ReText` 主要给 `layout` 用吗 还是说是通用的 如果通用的可以再组件菜单栏加上这个 `demo` 哈

2024-01-27 09:32 UTC, WitMiao commented
> 这个`ReText` 主要给 `layout` 用吗 还是说是通用的 如果通用的可以再组件菜单栏加上这个 `demo` 哈

通用的，好，那晚些我加个demo

2024-01-27 16:20 UTC, WitMiao commented
@xiaoxian521 demo页已加上，tippy 的引入方式改成Composition API了，之前用Directive方式时启用就后无法禁用

2024-01-27 17:10 UTC, xiaoxian521 commented
1. 菜单折叠后，有子集的菜单，显示位置不应该往右偏移
<img width="511" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/76d4433e-61b7-43da-89ec-2aa0a0f27d29">

2.如果是从左侧菜单折叠后，切换到顶部菜单模式，有子集的菜单文字不显示了
<img width="1609" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/1a206fc5-b320-4c39-b7d2-4a4aab717d94">
<img width="1677" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/d82c5064-f3d4-41f0-9708-affe7adfc492">

3.混合菜单模式，左侧菜单文字消失
<img width="1679" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/b904df4d-01f4-4309-b71d-dd0c12f1110f">

2024-01-28 07:40 UTC, WitMiao commented
> 1. 菜单折叠后，有子集的菜单，显示位置不应该往右偏移
> 
> <img alt="image" width="511" src="https://private-user-images.githubusercontent.com/44761321/300193444-76d4433e-61b7-43da-89ec-2aa0a0f27d29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MjI5ODIsIm5iZiI6MTcwNjQyMjY4MiwicGF0aCI6Ii80NDc2MTMyMS8zMDAxOTM0NDQtNzZkNDQzM2UtNjFiNy00M2RhLTg5ZWMtMmFhMGEwZjI3ZDI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDA2MTgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1MWU3NzE5MDQ3OTNkMDUwZjk3MjkzNTc0OTUyNzAyMjExODEyOTZiOTk2MDdmNDQ3MmQ3NDlkNmI4MmZiNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rAIjXAimLLMRryALsQzze78re5dQ58Eom5XmuTyJDgs">
> 2.如果是从左侧菜单折叠后，切换到顶部菜单模式，有子集的菜单文字不显示了 <img alt="image" width="1609" src="https://private-user-images.githubusercontent.com/44761321/300194060-1a206fc5-b320-4c39-b7d2-4a4aab717d94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MjI5ODIsIm5iZiI6MTcwNjQyMjY4MiwicGF0aCI6Ii80NDc2MTMyMS8zMDAxOTQwNjAtMWEyMDZmYzUtYjMyMC00YzM5LWI3ZDItNGE0YWFiNzE3ZDk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDA2MTgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlOGYwYWY2NTBlM2Q1NjBiYTQzNjczNmUyZDBjNTk3Y2E1ZGY0ODkzZWJkZGJlN2EzOWY2OGQ4NTVjZWEyYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sSDdijxicsaTNuOMIKhIZop_KndvfVD45BpiQcUgI_4"> <img alt="image" width="1677" src="https://private-user-images.githubusercontent.com/44761321/300194114-d82c5064-f3d4-41f0-9708-affe7adfc492.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MjI5ODIsIm5iZiI6MTcwNjQyMjY4MiwicGF0aCI6Ii80NDc2MTMyMS8zMDAxOTQxMTQtZDgyYzUwNjQtZjNkNC00MWYwLTk3MDgtYWZmZTdhZGZjNDkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDA2MTgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzYjBmZDE3MDNiNzk2NjgzNjRhY2E2ZmQzOGMxM2RlOGQ1NGJkZjE4ZWY1ZmMzNTRkNDgyMzE2ZjlhNmU3MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jKwIMCWjHxJ1xT2tYc1Ry5k5dUC0tkgK9eyzc5w330Y">
> 
> 3.混合菜单模式，左侧菜单文字消失 <img alt="image" width="1679" src="https://private-user-images.githubusercontent.com/44761321/300194219-b904df4d-01f4-4309-b71d-dd0c12f1110f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MjI5ODIsIm5iZiI6MTcwNjQyMjY4MiwicGF0aCI6Ii80NDc2MTMyMS8zMDAxOTQyMTktYjkwNGRmNGQtMDFmNC00MzA5LWI3MWQtZGQwYzEyZjExMTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDA2MTgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0ZjQ0M2Y1ZjhlZjkxYTE4ZDhiYjNkODNmZWE5ZWU2ZTkyMmNiMmI4ZTllMmRmNTZmYWVkNjk2MTE4YjYxYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8A7Kop9Ms0GXznAD7kSYDXnbTVqNG0v0hsoGQoM1LJ8">

修复了，再看看

2024-01-28 07:43 UTC, xiaoxian521 requested changes

2024-01-28 07:43 UTC, xiaoxian521 commented on src/layout/components/sidebar/sidebarItem.vue
> +import { en } from "@faker-js/faker";
此处是多余的吗

2024-01-28 07:43 UTC, xiaoxian521 commented on src/layout/components/sidebar/sidebarItem.vue
> +import { en } from "@faker-js/faker";
import { en } from "@faker-js/faker";

2024-01-28 07:56 UTC, WitMiao commented on src/layout/components/sidebar/sidebarItem.vue
> +import { en } from "@faker-js/faker";
是的，auto import插件加进来的，没注意，去掉了

2024-01-28 08:14 UTC, xiaoxian521 commented
整体测下来 没啥问题 我们将它放在`5.1.0`版本发布吧，还需要更多的测试！
感谢你的贡献❤️

2024-01-30 04:29 UTC, xiaoxian521 commented
嘿 我打算尽早合并它 以免后续突出

下图这个`demo`是什么意思呢 操作看似没啥变化
<img width="762" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/d5a0bea3-7d4e-4382-9e0a-dd1a0000012f">

2024-01-30 04:29 UTC, xiaoxian521 approved these changes

2024-01-31 10:36 UTC, WitMiao commented
> 嘿 我打算尽早合并它 以免后续突出
> 
> 下图这个`demo`是什么意思呢 操作看似没啥变化 <img alt="image" width="762" src="https://private-user-images.githubusercontent.com/44761321/300679808-d5a0bea3-7d4e-4382-9e0a-dd1a0000012f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTc1ODYsIm5iZiI6MTcwNjY5NzI4NiwicGF0aCI6Ii80NDc2MTMyMS8zMDA2Nzk4MDgtZDVhMGJlYTMtN2Q0ZS00MzgyLTllMGEtZGQxYTAwMDAwMTJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDEwMzQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlOWEwMWUxOTExOTgzOWY0M2I0ODc4Yjk0N2NlNDA0ODNiZDFmMjliNTQ3YmVjZmNiN2Y5Zjk3YzdlMjA5MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V-vfIf13oz9bTPCn6J66aVwl9HpXnBaaNZiE4dC15Kg">

是关闭监听的demo，关闭后就不能重新修改tooltip内容了，所以按钮点了没效果

2024-01-31 10:47 UTC, WitMiao commented
优化了一下这个demo

2024-02-02 03:53 UTC, WitMiao commented
问个题外话，有考虑把tailwindcss换成[unocss](https://unocss.dev/)的计划么，我项目有改过，需要的话可提个pr

2024-02-02 07:28 UTC, xiaoxian521 commented
> 问个题外话，有考虑把tailwindcss换成[unocss](https://unocss.dev/)的计划么，我项目有改过，需要的话可提个pr

不考虑 谢谢

2024-02-02 07:30 UTC, WitMiao commented
> > 问个题外话，有考虑把tailwindcss换成[unocss](https://unocss.dev/)的计划么，我项目有改过，需要的话可提个pr
> 
> 不考虑 谢谢

OK

2024-02-05 03:20 UTC, WitMiao commented
@xiaoxian521 感觉这两个监听关闭参数有点画蛇添足，如果你也觉得没必要，我就把它们去掉吧

2024-02-05 03:27 UTC, xiaoxian521 commented
> @xiaoxian521 感觉这两个监听关闭参数有点画蛇添足，如果你也觉得没必要，我就把它们去掉吧

如果有监听默认不开启哈 要不然放到导航会带来性能问题

2024-02-05 03:29 UTC, WitMiao commented
> > @xiaoxian521 感觉这两个监听关闭参数有点画蛇添足，如果你也觉得没必要，我就把它们去掉吧
> 
> 如果有监听默认不开启哈 要不然放到导航会带来性能问题

好的，那我改下默认值

2024-02-05 03:30 UTC, xiaoxian521 commented
嗯嗯 明天会开始合并处理

2024-02-05 06:12 UTC, WitMiao commented
已修改完毕

2024-02-08 10:43 UTC, xiaoxian521 commented
综合考虑下来 https://github.com/pure-admin/vue-pure-admin/pull/898/files#diff-a585d5de39e3d0770d1f7da1adf0fe6504ea67c92461a942423560adf87312e1R87 此次的监听可能会带来性能问题
可以改为当鼠标覆盖上去时 做 tooltip 的显隐处理

2024-02-08 10:45 UTC, xiaoxian521 commented
类似这种处理 https://github.com/pure-admin/vue-pure-admin/pull/898/files#diff-50efc68ad1e48b35f66d1f5b57e525d3adf155950d156ab19056716b6d8ac607L248

2024-02-15 17:53 UTC, WitMiao commented
> 类似这种处理 [#898 (files)](https://github.com/pure-admin/vue-pure-admin/pull/898/files#diff-50efc68ad1e48b35f66d1f5b57e525d3adf155950d156ab19056716b6d8ac607L248)
> 
> 用鼠标覆盖做处理后 此处 [#898 (files)](https://github.com/pure-admin/vue-pure-admin/pull/898/files#diff-a585d5de39e3d0770d1f7da1adf0fe6504ea67c92461a942423560adf87312e1R79) 应该也不需要监听了

感谢反馈，已完成修改，成功把监听和计算属性都去除了

2024-02-19 05:34 UTC, xiaoxian521 commented
感谢跟进。非常好的组件和优化！❤️

2024-02-19 05:36 UTC, merged